# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FCFS.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(872, 859)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("scheduler (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 50, 651, 101))
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("font: 16pt \"Montserrat\"; color: black ; font-weight: bold;\n"
" font-weight:bold;")
        self.label.setObjectName("label")
        self.toolButton_6 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_6.setGeometry(QtCore.QRect(290, 720, 281, 91))
        self.toolButton_6.setStyleSheet("font: 14pt \"Montserrat\";  font-weight: bold; color:#FF5757;  font-size: 14;")
        self.toolButton_6.setObjectName("toolButton_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(450, 260, 411, 71))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("font: 12pt \"Montserrat\"; color: black; font-weight: bold;")
        self.label_4.setObjectName("label_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(310, 180, 101, 51))
        self.plainTextEdit.setStyleSheet("border: 2px  solid black;  font: 55 20pt")
        self.plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(450, 330, 301, 371))
        self.plainTextEdit_3.setStyleSheet("border: 2px  solid black; font: 75 20pt")
        self.plainTextEdit_3.setPlainText("")
        self.plainTextEdit_3.setOverwriteMode(False)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 280, 341, 41))
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("font: 12pt \"Montserrat\"; color: black; font-weight: bold;")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 150, 231, 101))
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("font: 12pt \"Montserrat\"; color: black; font-weight: bold;")
        self.label_5.setObjectName("label_5")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(60, 330, 291, 371))
        self.plainTextEdit_4.setStyleSheet("border: 2px  solid black;  font: 55 20pt")
        self.plainTextEdit_4.setPlainText("")
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CPU Job Scheduler"))
        self.label.setText(_translate("MainWindow", "PLEASE ENTER THE FOLLOWING INPUTS:"))
        self.toolButton_6.setText(_translate("MainWindow", "RUN"))
        self.label_4.setText(_translate("MainWindow", "Burst Time of Each Process"))
        self.label_3.setText(_translate("MainWindow", "Arrival time of Each Process"))
        self.label_5.setText(_translate("MainWindow", "Number of Processes"))
